//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFVSMQTTMessageDisplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFVSChannelAlarm
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> AlarmLevel { get; set; }
        public Nullable<double> Possibility { get; set; }
        public Nullable<double> CenterPosition { get; set; }
        public Nullable<double> EventWidth { get; set; }
        public Nullable<System.DateTime> FirstPushTime { get; set; }
        public Nullable<System.DateTime> LastPushTime { get; set; }
        public Nullable<double> MaxIntensity { get; set; }
        public string SensorID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<System.DateTime> PushTime { get; set; }
    }
}
